spring.application.name=subscription-system
spring.datasource.url=jdbc:mysql://localhost:3306/subscription_system
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
server.error.include-binding-errors=always
